### ISSUE TITLE
minitf.py wrong import

### ISSUE THREAD

**Issue by michamein** [HebrewTools/Reader#4]
The import statement in line 3 should be 
```python
from tf.core.api import NodeFeatures, EdgeFeatures
```
because the class names are <code>NodeFeatures</code> and <code>EdgeFeatures</code>
As of now it is
```python
from tf.core.api import NodeFeature, EdgeFeature
```
And it produces an error, because <code>tf</code> does not have the classes <code>NodeFeature</code> and <code>EdgeFeature</code>

**Comment by camilstaps** [comment]
Thanks for the report. 

The upstream has too frequent backwards incompatible changes for me to keep up with it, especially since most people will just use https://reader.hebrewtools.org. This runs  in docker, so it’s easy to install an older version (see setup.py).

But if you or someone else is willing to put in the time to see what has changed and make a pull request, I’m happy to do a review.

**Comment by michamein** [comment]
Thank you for your answer.

The docker image should be easy enough.
